<?php

/**
 * Perú cities
 *
 * @author   Dropi SAS. <desarrollador7@dropi.co>
 * @version  1.0
 */
global $places;

$places['PE'] = array(
    'PE-AMA' => array(
        "CHACHAPOYAS",
        "ASUNCION",
        "BALSAS",
        "CHETO",
        "CHILIQUIN",
        "CHUQUIBAMBA",
        "GRANADA",
        "HUANCAS",
        "LA JALCA",
        "LEIMEBAMBA",
        "LEVANTO",
        "MAGDALENA",
        "MARISCAL CASTILLA",
        "MOLINOPAMPA",
        "MONTEVIDEO",
        "OLLEROS",
        "QUINJALCA",
        "SAN FRANCISCO DE DAGUAS",
        "SAN ISIDRO DE MAINO",
        "SOLOCO",
        "SONCHE",
        "BAGUA",
        "ARAMANGO",
        "COPALLIN",
        "EL PARCO",
        "IMAZA",
        "LA PECA",
        "JUMBILLA",
        "CHISQUILLA",
        "CHURUJA",
        "COROSHA",
        "CUISPES",
        "FLORIDA",
        "JAZAN",
        "RECTA",
        "SAN CARLOS",
        "SHIPASBAMBA",
        "VALERA",
        "YAMBRASBAMBA",
        "NIEVA",
        "EL CENEPA",
        "RIO SANTIAGO",
        "LAMUD",
        "CAMPORREDONDO",
        "COCABAMBA",
        "COLCAMAR",
        "CONILA",
        "INGUILPATA",
        "LONGUITA",
        "LONYA CHICO",
        "LUYA",
        "LUYA VIEJO",
        "MARIA",
        "OCALLI",
        "OCUMAL",
        "PISUQUIA",
        "PROVIDENCIA",
        "SAN CRISTOBAL",
        "SAN FRANCISCO DE YESO",
        "SAN JERONIMO",
        "SAN JUAN DE LOPECANCHA",
        "SANTA CATALINA",
        "SANTO TOMAS",
        "TINGO",
        "TRITA",
        "SAN NICOLAS",
        "CHIRIMOTO",
        "COCHAMAL",
        "HUAMBO",
        "LIMABAMBA",
        "LONGAR",
        "MARISCAL BENAVIDES",
        "MILPUC",
        "OMIA",
        "SANTA ROSA",
        "TOTORA",
        "VISTA ALEGRE",
        "BAGUA GRANDE",
        "CAJARURO",
        "CUMBA",
        "EL MILAGRO",
        "JAMALCA",
        "LONYA GRANDE",
        "YAMON"
    ),
    'PE-ANC' => array(
        "HUARAZ",
        "COCHABAMBA",
        "COLCABAMBA",
        "HUANCHAY",
        "INDEPENDENCIA",
        "JANGAS",
        "LA LIBERTAD",
        "OLLEROS",
        "PAMPAS GRANDE",
        "PARIACOTO",
        "PIRA",
        "TARICA",
        "AIJA",
        "CORIS",
        "HUACLLAN",
        "LA MERCED",
        "SUCCHA",
        "LLAMELLIN",
        "ACZO",
        "CHACCHO",
        "CHINGAS",
        "MIRGAS",
        "SAN JUAN DE RONTOY",
        "CHACAS",
        "ACOCHACA",
        "CHIQUIAN",
        "ABELARDO PARDO LEZAMETA",
        "ANTONIO RAYMONDI",
        "AQUIA",
        "CAJACAY",
        "CANIS",
        "COLQUIOC",
        "HUALLANCA",
        "HUASTA",
        "HUAYLLACAYAN",
        "LA PRIMAVERA",
        "MANGAS",
        "PACLLON",
        "SAN MIGUEL DE CORPANQUI",
        "TICLLOS",
        "CARHUAZ",
        "ACOPAMPA",
        "AMASHCA",
        "ANTA",
        "ATAQUERO",
        "MARCARA",
        "PARIAHUANCA",
        "SAN MIGUEL DE ACO",
        "SHILLA",
        "TINCO",
        "YUNGAR",
        "SAN LUIS",
        "SAN NICOLAS",
        "YAUYA",
        "CASMA",
        "BUENA VISTA ALTA",
        "COMANDANTE NOEL",
        "YAUTAN",
        "CORONGO",
        "ACO",
        "BAMBAS",
        "CUSCA",
        "LA PAMPA",
        "YANAC",
        "YUPAN",
        "HUARI",
        "ANRA",
        "CAJAY",
        "CHAVIN DE HUANTAR",
        "HUACACHI",
        "HUACCHIS",
        "HUACHIS",
        "HUANTAR",
        "MASIN",
        "PAUCAS",
        "PONTO",
        "RAHUAPAMPA",
        "RAPAYAN",
        "SAN MARCOS",
        "SAN PEDRO DE CHANA",
        "UCO",
        "HUARMEY",
        "COCHAPETI",
        "CULEBRAS",
        "HUAYAN",
        "MALVAS",
        "CARAZ",
        "HUALLANCA",
        "HUATA",
        "HUAYLAS",
        "MATO",
        "PAMPAROMAS",
        "PUEBLO LIBRE",
        "SANTA CRUZ",
        "SANTO TORIBIO",
        "YURACMARCA",
        "PISCOBAMBA",
        "CASCA",
        "ELEAZAR GUZMAN BARRON",
        "FIDEL OLIVAS ESCUDERO",
        "LLAMA",
        "LLUMPA",
        "LUCMA",
        "MUSGA",
        "OCROS",
        "ACAS",
        "CAJAMARQUILLA",
        "CARHUAPAMPA",
        "COCHAS",
        "CONGAS",
        "LLIPA",
        "SAN CRISTOBAL DE RAJAN",
        "SAN PEDRO",
        "SANTIAGO DE CHILCAS",
        "CABANA",
        "BOLOGNESI",
        "CONCHUCOS",
        "HUACASCHUQUE",
        "HUANDOVAL",
        "LACABAMBA",
        "LLAPO",
        "PALLASCA",
        "PAMPAS",
        "SANTA ROSA",
        "TAUCA",
        "POMABAMBA",
        "HUAYLLAN",
        "PAROBAMBA",
        "QUINUABAMBA",
        "RECUAY",
        "CATAC",
        "COTAPARACO",
        "HUAYLLAPAMPA",
        "LLACLLIN",
        "MARCA",
        "PAMPAS CHICO",
        "PARARIN",
        "TAPACOCHA",
        "TICAPAMPA",
        "CHIMBOTE",
        "CACERES DEL PERU",
        "COISHCO",
        "MACATE",
        "MORO",
        "NEPEÑA",
        "SAMANCO",
        "SANTA",
        "NUEVO CHIMBOTE",
        "SIHUAS",
        "ACOBAMBA",
        "ALFONSO UGARTE",
        "CASHAPAMPA",
        "CHINGALPO",
        "HUAYLLABAMBA",
        "QUICHES",
        "RAGASH",
        "SAN JUAN",
        "SICSIBAMBA",
        "YUNGAY",
        "CASCAPARA",
        "MANCOS",
        "MATACOTO",
        "QUILLO",
        "RANRAHIRCA",
        "SHUPLUY",
        "YANAMA"
    ),

    'PE-APU' => array(
        "ABANCAY",
        "CHACOCHE",
        "CIRCA",
        "CURAHUASI",
        "HUANIPACA",
        "LAMBRAMA",
        "PICHIRHUA",
        "SAN PEDRO DE CACHORA",
        "TAMBURCO",
        "ANDAHUAYLAS",
        "ANDARAPA",
        "CHIARA",
        "HUANCARAMA",
        "HUANCARAY",
        "HUAYANA",
        "KISHUARA",
        "PACOBAMBA",
        "PACUCHA",
        "PAMPACHIRI",
        "POMACOCHA",
        "SAN ANTONIO DE CACHI",
        "SAN JERONIMO",
        "SAN MIGUEL DE CHACCRAMPA",
        "SANTA MARIA DE CHICMO",
        "TALAVERA",
        "TUMAY HUARACA",
        "TURPO",
        "KAQUIABAMBA",
        "JOSÉ MARIA ARGUEDAS",
        "ANTABAMBA",
        "EL ORO",
        "HUAQUIRCA",
        "JUAN ESPINOZA MEDRANO",
        "OROPESA",
        "PACHACONAS",
        "SABAINO",
        "CHALHUANCA",
        "CAPAYA",
        "CARAYBAMBA",
        "CHAPIMARCA",
        "COLCABAMBA",
        "COTARUSE",
        "HUAYLLO",
        "JUSTO APU SAHUARAURA",
        "LUCRE",
        "POCOHUANCA",
        "SAN JUAN DE CHACÑA",
        "SAÑAYCA",
        "SORAYA",
        "TAPAIRIHUA",
        "TINTAY",
        "TORAYA",
        "YANACA",
        "TAMBOBAMBA",
        "COTABAMBAS",
        "COYLLURQUI",
        "HAQUIRA",
        "MARA",
        "CHALLHUAHUACHO",
        "CHINCHEROS",
        "ANCO_HUALLO",
        "COCHARCAS",
        "HUACCANA",
        "OCOBAMBA",
        "ONGOY",
        "URANMARCA",
        "RANRACANCHA",
        "CHUQUIBAMBILLA",
        "CURPAHUASI",
        "GAMARRA",
        "HUAYLLATI",
        "MAMARA",
        "MICAELA BASTIDAS",
        "PATAYPAMPA",
        "PROGRESO",
        "SAN ANTONIO",
        "SANTA ROSA",
        "TURPAY",
        "VILCABAMBA",
        "VIRUNDO",
        "CURASCO"
    ),
    'PE-ARE' => array(
        "AREQUIPA",
        "ALTO SELVA ALEGRE",
        "CAYMA",
        "CERRO COLORADO",
        "CHARACATO",
        "CHIGUATA",
        "JACOBO HUNTER",
        "LA JOYA",
        "MARIANO MELGAR",
        "MIRAFLORES",
        "MOLLEBAYA",
        "PAUCARPATA",
        "POCSI",
        "POLOBAYA",
        "QUEQUEÑA",
        "SABANDIA",
        "SACHACA",
        "SAN JUAN DE SIGUAS",
        "SAN JUAN DE TARUCANI",
        "SANTA ISABEL DE SIGUAS",
        "SANTA RITA DE SIGUAS",
        "SOCABAYA",
        "TIABAYA",
        "UCHUMAYO",
        "VITOR",
        "YANAHUARA",
        "YARABAMBA",
        "YURA",
        "JOSÉ LUIS BUSTAMANTE Y RIVERO",
        "CAMANA",
        "JOSÉ MARIA QUIMPER",
        "MARIANO NICOLAS VALCARCEL",
        "MARISCAL CACERES",
        "NICOLAS DE PIEROLA",
        "OCOÑA",
        "QUILCA",
        "SAMUEL PASTOR",
        "CARAVELI",
        "ACARI",
        "ATICO",
        "ATIQUIPA",
        "BELLA UNION",
        "CAHUACHO",
        "CHALA",
        "CHAPARRA",
        "HUANUHUANU",
        "JAQUI",
        "LOMAS",
        "QUICACHA",
        "YAUCA",
        "APLAO",
        "ANDAGUA",
        "AYO",
        "CHACHAS",
        "CHILCAYMARCA",
        "CHOCO",
        "HUANCARQUI",
        "MACHAGUAY",
        "ORCOPAMPA",
        "PAMPACOLCA",
        "TIPAN",
        "UÑON",
        "URACA",
        "VIRACO",
        "CHIVAY",
        "ACHOMA",
        "CABANACONDE",
        "CALLALLI",
        "CAYLLOMA",
        "COPORAQUE",
        "HUAMBO",
        "HUANCA",
        "ICHUPAMPA",
        "LARI",
        "LLUTA",
        "MACA",
        "MADRIGAL",
        "SAN ANTONIO DE CHUCA",
        "SIBAYO",
        "TAPAY",
        "TISCO",
        "TUTI",
        "YANQUE",
        "MAJES",
        "CHUQUIBAMBA",
        "ANDARAY",
        "CAYARANI",
        "CHICHAS",
        "IRAY",
        "RIO GRANDE",
        "SALAMANCA",
        "YANAQUIHUA",
        "MOLLENDO",
        "COCACHACRA",
        "DEAN VALDIVIA",
        "ISLAY",
        "MEJIA",
        "PUNTA DE BOMBON",
        "COTAHUASI",
        "ALCA",
        "CHARCANA",
        "HUAYNACOTAS",
        "PAMPAMARCA",
        "PUYCA",
        "QUECHUALLA",
        "SAYLA",
        "TAURIA",
        "TOMEPAMPA",
        "TORO",
    ),
    'PE-AYA' => array(
        "AYACUCHO",
        "ACOCRO",
        "ACOS VINCHOS",
        "CARMEN ALTO",
        "CHIARA",
        "OCROS",
        "PACAYCASA",
        "QUINUA",
        "SAN JOSÉ DE TICLLAS",
        "SAN JUAN BAUTISTA",
        "SANTIAGO DE PISCHA",
        "SOCOS",
        "TAMBILLO",
        "VINCHOS",
        "JESUS NAZARENO",
        "ANDRÉS AVELINO CACERES DORREGARAY",
        "CANGALLO",
        "CHUSCHI",
        "LOS MOROCHUCOS",
        "MARIA PARADO DE BELLIDO",
        "PARAS",
        "TOTOS",
        "SANCOS",
        "CARAPO",
        "SACSAMARCA",
        "SANTIAGO DE LUCANAMARCA",
        "HUANTA",
        "AYAHUANCO",
        "HUAMANGUILLA",
        "IGUAIN",
        "LURICOCHA",
        "SANTILLANA",
        "SIVIA",
        "LLOCHEGUA",
        "CANAYRE",
        "UCHURACCAY",
        "PUCACOLPA",
        "SAN MIGUEL",
        "ANCO",
        "AYNA",
        "CHILCAS",
        "CHUNGUI",
        "LUIS CARRANZA",
        "SANTA ROSA",
        "TAMBO",
        "SAMUGARI",
        "ANCHIHUAY",
        "PUQUIO",
        "AUCARA",
        "CABANA",
        "CARMEN SALCEDO",
        "CHAVIÑA",
        "CHIPAO",
        "HUAC-HUAS",
        "LARAMATE",
        "LEONCIO PRADO",
        "LLAUTA",
        "LUCANAS",
        "OCAÑA",
        "OTOCA",
        "SAISA",
        "SAN CRISTOBAL",
        "SAN JUAN",
        "SAN PEDRO",
        "SAN PEDRO DE PALCO",
        "SANCOS",
        "SANTA ANA DE HUAYCAHUACHO",
        "SANTA LUCIA",
        "CORACORA",
        "CHUMPI",
        "CORONEL CASTAÑEDA",
        "PACAPAUSA",
        "PULLO",
        "PUYUSCA",
        "SAN FRANCISCO DE RAVACAYCO",
        "UPAHUACHO",
        "PAUSA",
        "COLTA",
        "CORCULLA",
        "LAMPA",
        "MARCABAMBA",
        "OYOLO",
        "PARARCA",
        "SAN JAVIER DE ALPABAMBA",
        "SAN JOSÉ DE USHUA",
        "SARA SARA",
        "QUEROBAMBA",
        "BELÉN",
        "CHALCOS",
        "CHILCAYOC",
        "HUACAÑA",
        "MORCOLLA",
        "PAICO",
        "SAN PEDRO DE LARCAY",
        "SAN SALVADOR DE QUIJE",
        "SANTIAGO DE PAUCARAY",
        "SORAS",
        "HUANCAPI",
        "ALCAMENCA",
        "APONGO",
        "ASQUIPATA",
        "CANARIA",
        "CAYARA",
        "COLCA",
        "HUAMANQUIQUIA",
        "HUANCARAYLLA",
        "HUAYA",
        "SARHUA",
        "VILCANCHOS",
        "VILCAS HUAMAN",
        "ACCOMARCA",
        "CARHUANCA",
        "CONCEPCION",
        "HUAMBALPA",
        "INDEPENDENCIA",
        "SAURAMA",
        "VISCHONGO",
    ),
    'PE-CAJ' => array(
        "CAJAMARCA",
        "ASUNCION",
        "CHETILLA",
        "COSPAN",
        "ENCAÑADA",
        "JESUS",
        "LLACANORA",
        "LOS BAÑOS DEL INCA",
        "MAGDALENA",
        "MATARA",
        "NAMORA",
        "SAN JUAN",
        "",
        "CAJABAMBA",
        "CACHACHI",
        "CONDEBAMBA",
        "SITACOCHA",
        "",
        "CELENDIN",
        "CHUMUCH",
        "CORTEGANA",
        "HUASMIN",
        "JORGE CHAVEZ",
        "JOSÉ GALVEZ",
        "MIGUEL IGLESIAS",
        "OXAMARCA",
        "SOROCHUCO",
        "SUCRE",
        "UTCO",
        "LA LIBERTAD DE PALLAN",
        "",
        "CHOTA",
        "ANGUIA",
        "CHADIN",
        "CHIGUIRIP",
        "CHIMBAN",
        "CHOROPAMPA",
        "COCHABAMBA",
        "CONCHAN",
        "HUAMBOS",
        "LAJAS",
        "LLAMA",
        "MIRACOSTA",
        "PACCHA",
        "PION",
        "QUEROCOTO",
        "SAN JUAN DE LICUPIS",
        "TACABAMBA",
        "TOCMOCHE",
        "CHALAMARCA",
        "",
        "CONTUMAZA",
        "CHILETE",
        "CUPISNIQUE",
        "GUZMANGO",
        "SAN BENITO",
        "SANTA CRUZ DE TOLEDO",
        "TANTARICA",
        "YONAN",
        "",
        "CUTERVO",
        "CALLAYUC",
        "CHOROS",
        "CUJILLO",
        "LA RAMADA",
        "PIMPINGOS",
        "QUEROCOTILLO",
        "SAN ANDRÉS DE CUTERVO",
        "SAN JUAN DE CUTERVO",
        "SAN LUIS DE LUCMA",
        "SANTA CRUZ",
        "SANTO DOMINGO DE LA CAPILLA",
        "SANTO TOMAS",
        "SOCOTA",
        "TORIBIO CASANOVA",
        "",
        "BAMBAMARCA",
        "CHUGUR",
        "HUALGAYOC",
        "",
        "JAÉN",
        "BELLAVISTA",
        "CHONTALI",
        "COLASAY",
        "HUABAL",
        "LAS PIRIAS",
        "POMAHUACA",
        "PUCARA",
        "SALLIQUE",
        "SAN FELIPE",
        "SAN JOSÉ DEL ALTO",
        "SANTA ROSA",
        "",
        "SAN IGNACIO",
        "CHIRINOS",
        "HUARANGO",
        "LA COIPA",
        "NAMBALLE",
        "SAN JOSÉ DE LOURDES",
        "TABACONAS",
        "",
        "PEDRO GALVEZ",
        "CHANCAY",
        "EDUARDO VILLANUEVA",
        "GREGORIO PITA",
        "ICHOCAN",
        "JOSÉ MANUEL QUIROZ",
        "JOSÉ SABOGAL",
        "",
        "SAN MIGUEL",
        "BOLIVAR",
        "CALQUIS",
        "CATILLUC",
        "EL PRADO",
        "LA FLORIDA",
        "LLAPA",
        "NANCHOC",
        "NIEPOS",
        "SAN GREGORIO",
        "SAN SILVESTRE DE COCHAN",
        "TONGOD",
        "UNION AGUA BLANCA",
        "",
        "SAN PABLO",
        "SAN BERNARDINO",
        "SAN LUIS",
        "TUMBADEN",
        "",
        "SANTA CRUZ",
        "ANDABAMBA",
        "CATACHE",
        "CHANCAYBAÑOS",
        "LA ESPERANZA",
        "NINABAMBA",
        "PULAN",
        "SAUCEPAMPA",
        "SEXI",
        "UTICYACU",
        "YAUYUCAN",

    ),
    'PE-CAL' => array(
        "CALLAO",
        "BELLAVISTA",
        "CARMEN DE LA LEGUA REYNOSO",
        "LA PERLA",
        "LA PUNTA",
        "VENTANILLA",
        "MI PERU",
    ),
    'PE-CUS' => array(
        "CUSCO",
        "CCORCA",
        "POROY",
        "SAN JERONIMO",
        "SAN SEBASTIAN",
        "SANTIAGO",
        "SAYLLA",
        "WANCHAQ",
        "",
        "ACOMAYO",
        "ACOPIA",
        "ACOS",
        "MOSOC LLACTA",
        "POMACANCHI",
        "RONDOCAN",
        "SANGARARA",
        "",
        "ANTA",
        "ANCAHUASI",
        "CACHIMAYO",
        "CHINCHAYPUJIO",
        "HUAROCONDO",
        "LIMATAMBO",
        "MOLLEPATA",
        "PUCYURA",
        "ZURITE",
        "",
        "CALCA",
        "COYA",
        "LAMAY",
        "LARES",
        "PISAC",
        "SAN SALVADOR",
        "TARAY",
        "YANATILE",
        "",
        "YANAOCA",
        "CHECCA",
        "KUNTURKANKI",
        "LANGUI",
        "LAYO",
        "PAMPAMARCA",
        "QUEHUE",
        "TUPAC AMARU",
        "",
        "SICUANI",
        "CHECACUPE",
        "COMBAPATA",
        "MARANGANI",
        "PITUMARCA",
        "SAN PABLO",
        "SAN PEDRO",
        "TINTA",
        "",
        "SANTO TOMAS",
        "CAPACMARCA",
        "CHAMACA",
        "COLQUEMARCA",
        "LIVITACA",
        "LLUSCO",
        "QUIÑOTA",
        "VELILLE",
        "",
        "ESPINAR",
        "CONDOROMA",
        "COPORAQUE",
        "OCORURO",
        "PALLPATA",
        "PICHIGUA",
        "SUYCKUTAMBO",
        "ALTO PICHIGUA",
        "",
        "SANTA ANA",
        "ECHARATE",
        "HUAYOPATA",
        "MARANURA",
        "OCOBAMBA",
        "QUELLOUNO",
        "KIMBIRI",
        "SANTA TERESA",
        "VILCABAMBA",
        "PICHARI",
        "INKAWASI",
        "VILLA VIRGEN",
        "VILLA KINTIARINA",
        "",
        "PARURO",
        "ACCHA",
        "CCAPI",
        "COLCHA",
        "HUANOQUITE",
        "OMACHA",
        "PACCARITAMBO",
        "PILLPINTO",
        "YAURISQUE",
        "",
        "PAUCARTAMBO",
        "CAICAY",
        "CHALLABAMBA",
        "COLQUEPATA",
        "HUANCARANI",
        "KOSÑIPATA",
        "",
        "URCOS",
        "ANDAHUAYLILLAS",
        "CAMANTI",
        "CCARHUAYO",
        "CCATCA",
        "CUSIPATA",
        "HUARO",
        "LUCRE",
        "MARCAPATA",
        "OCONGATE",
        "OROPESA",
        "QUIQUIJANA",
        "",
        "URUBAMBA",
        "CHINCHERO",
        "HUAYLLABAMBA",
        "MACHUPICCHU",
        "MARAS",
        "OLLANTAYTAMBO",
        "YUCAY"
    ),
    'PE-HUV' => array(
        "HUANCAVELICA",
        "ACOBAMBILLA",
        "ACORIA",
        "CONAYCA",
        "CUENCA",
        "HUACHOCOLPA",
        "HUAYLLAHUARA",
        "IZCUCHACA",
        "LARIA",
        "MANTA",
        "MARISCAL CACERES",
        "MOYA",
        "NUEVO OCCORO",
        "PALCA",
        "PILCHACA",
        "VILCA",
        "YAULI",
        "ASCENSION",
        "HUANDO",
        "ACOBAMBA",
        "ANDABAMBA",
        "ANTA",
        "CAJA",
        "MARCAS",
        "PAUCARA",
        "POMACOCHA",
        "ROSARIO",
        "LIRCAY",
        "ANCHONGA",
        "CALLANMARCA",
        "CCOCHACCASA",
        "CHINCHO",
        "CONGALLA",
        "HUANCA-HUANCA",
        "HUAYLLAY GRANDE",
        "JULCAMARCA",
        "SAN ANTONIO DE ANTAPARCO",
        "SANTO TOMAS DE PATA",
        "SECCLLA",
        "CASTROVIRREYNA",
        "ARMA",
        "AURAHUA",
        "CAPILLAS",
        "CHUPAMARCA",
        "COCAS",
        "HUACHOS",
        "HUAMATAMBO",
        "MOLLEPAMPA",
        "SAN JUAN",
        "SANTA ANA",
        "TANTARA",
        "TICRAPO",
        "CHURCAMPA",
        "ANCO",
        "CHINCHIHUASI",
        "EL CARMEN",
        "LA MERCED",
        "LOCROJA",
        "PAUCARBAMBA",
        "SAN MIGUEL DE MAYOCC",
        "SAN PEDRO DE CORIS",
        "PACHAMARCA",
        "COSME",
        "HUAYTARA",
        "AYAVI",
        "CORDOVA",
        "HUAYACUNDO ARMA",
        "LARAMARCA",
        "OCOYO",
        "PILPICHACA",
        "QUERCO",
        "QUITO-ARMA",
        "SAN ANTONIO DE CUSICANCHA",
        "SAN FRANCISCO DE SANGAYAICO",
        "SAN ISIDRO",
        "SANTIAGO DE CHOCORVOS",
        "SANTIAGO DE QUIRAHUARA",
        "SANTO DOMINGO DE CAPILLAS",
        "TAMBO",
        "PAMPAS",
        "ACOSTAMBO",
        "ACRAQUIA",
        "AHUAYCHA",
        "COLCABAMBA",
        "DANIEL HERNANDEZ",
        "HUACHOCOLPA",
        "HUARIBAMBA",
        "ÑAHUIMPUQUIO",
        "PAZOS",
        "QUISHUAR",
        "SALCABAMBA",
        "SALCAHUASI",
        "SAN MARCOS DE ROCCHAC",
        "SURCUBAMBA",
        "TINTAY PUNCU",
        "QUICHUAS",
        "ANDAYMARCA"
    ),
    'PE-HUC' => array(
        "HUANUCO",
        "AMARILIS",
        "CHINCHAO",
        "CHURUBAMBA",
        "MARGOS",
        "QUISQUI (KICHKI)",
        "SAN FRANCISCO DE CAYRAN",
        "SAN PEDRO DE CHAULAN",
        "SANTA MARIA DEL VALLE",
        "YARUMAYO",
        "PILLCO MARCA",
        "YACUS",
        "AMBO",
        "CAYNA",
        "COLPAS",
        "CONCHAMARCA",
        "HUACAR",
        "SAN FRANCISCO",
        "SAN RAFAEL",
        "TOMAY KICHWA",
        "LA UNION",
        "CHUQUIS",
        "MARIAS",
        "PACHAS",
        "QUIVILLA",
        "RIPAN",
        "SHUNQUI",
        "SILLAPATA",
        "YANAS",
        "HUACAYBAMBA",
        "CANCHABAMBA",
        "COCHABAMBA",
        "PINRA",
        "LLATA",
        "ARANCAY",
        "CHAVIN DE PARIARCA",
        "JACAS GRANDE",
        "JIRCAN",
        "MIRAFLORES",
        "MONZON",
        "PUNCHAO",
        "PUÑOS",
        "SINGA",
        "TANTAMAYO",
        "RUPA-RUPA",
        "DANIEL ALOMIA ROBLES",
        "HERMILIO VALDIZAN",
        "JOSÉ CRESPO Y CASTILLO",
        "LUYANDO",
        "MARIANO DAMASO BERAUN",
        "HUACRACHUCO",
        "CHOLON",
        "SAN BUENAVENTURA",
        "PANAO",
        "CHAGLLA",
        "MOLINO",
        "UMARI",
        "PUERTO INCA",
        "CODO DEL POZUZO",
        "HONORIA",
        "TOURNAVISTA",
        "YUYAPICHIS",
        "JESUS",
        "BAÑOS",
        "JIVIA",
        "QUEROPALCA",
        "RONDOS",
        "SAN FRANCISCO DE ASIS",
        "SAN MIGUEL DE CAURI",
        "CHAVINILLO",
        "CAHUAC",
        "CHACABAMBA",
        "APARICIO POMARES",
        "JACAS CHICO",
        "OBAS",
        "PAMPAMARCA",
        "CHORAS"
    ),
    'PE-ICA' => array(
        "ICA",
        "LA TINGUIÑA",
        "LOS AQUIJES",
        "OCUCAJE",
        "PACHACUTEC",
        "PARCONA",
        "PUEBLO NUEVO",
        "SALAS",
        "SAN JOSÉ DE LOS MOLINOS",
        "SAN JUAN BAUTISTA",
        "SANTIAGO",
        "SUBTANJALLA",
        "TATE",
        "YAUCA DEL ROSARIO",
        "CHINCHA ALTA",
        "ALTO LARAN",
        "CHAVIN",
        "CHINCHA BAJA",
        "EL CARMEN",
        "GROCIO PRADO",
        "PUEBLO NUEVO",
        "SAN JUAN DE YANAC",
        "SAN PEDRO DE HUACARPANA",
        "SUNAMPE",
        "TAMBO DE MORA",
        "NASCA",
        "CHANGUILLO",
        "EL INGENIO",
        "MARCONA",
        "VISTA ALEGRE",
        "PALPA",
        "LLIPATA",
        "RIO GRANDE",
        "SANTA CRUZ",
        "TIBILLO",
        "PISCO",
        "HUANCANO",
        "HUMAY",
        "INDEPENDENCIA",
        "PARACAS",
        "SAN ANDRÉS",
        "SAN CLEMENTE",
        "TUPAC AMARU INCA",
    ),
    'PE-JUN' => array(
        "HUANCAYO",
        "CARHUACALLANGA",
        "CHACAPAMPA",
        "CHICCHE",
        "CHILCA",
        "CHONGOS ALTO",
        "CHUPURO",
        "COLCA",
        "CULLHUAS",
        "EL TAMBO",
        "HUACRAPUQUIO",
        "HUALHUAS",
        "HUANCAN",
        "HUASICANCHA",
        "HUAYUCACHI",
        "INGENIO",
        "PARIAHUANCA",
        "PILCOMAYO",
        "PUCARA",
        "QUICHUAY",
        "QUILCAS",
        "SAN AGUSTIN",
        "SAN JERONIMO DE TUNAN",
        "SAÑO",
        "SAPALLANGA",
        "SICAYA",
        "SANTO DOMINGO DE ACOBAMBA",
        "VIQUES",
        "CONCEPCION",
        "ACO",
        "ANDAMARCA",
        "CHAMBARA",
        "COCHAS",
        "COMAS",
        "HEROINAS TOLEDO",
        "MANZANARES",
        "MARISCAL CASTILLA",
        "MATAHUASI",
        "MITO",
        "NUEVE DE JULIO",
        "ORCOTUNA",
        "SAN JOSÉ DE QUERO",
        "SANTA ROSA DE OCOPA",
        "CHANCHAMAYO",
        "PERENE",
        "PICHANAQUI",
        "SAN LUIS DE SHUARO",
        "SAN RAMON",
        "VITOC",
        "JAUJA",
        "ACOLLA",
        "APATA",
        "ATAURA",
        "CANCHAYLLO",
        "CURICACA",
        "EL MANTARO",
        "HUAMALI",
        "HUARIPAMPA",
        "HUERTAS",
        "JANJAILLO",
        "JULCAN",
        "LEONOR ORDOÑEZ",
        "LLOCLLAPAMPA",
        "MARCO",
        "MASMA",
        "MASMA CHICCHE",
        "MOLINOS",
        "MONOBAMBA",
        "MUQUI",
        "MUQUIYAUYO",
        "PACA",
        "PACCHA",
        "PANCAN",
        "PARCO",
        "POMACANCHA",
        "RICRAN",
        "SAN LORENZO",
        "SAN PEDRO DE CHUNAN",
        "SAUSA",
        "SINCOS",
        "TUNAN MARCA",
        "YAULI",
        "YAUYOS",
        "JUNIN",
        "CARHUAMAYO",
        "ONDORES",
        "ULCUMAYO",
        "SATIPO",
        "COVIRIALI",
        "LLAYLLA",
        "MAZAMARI",
        "PAMPA HERMOSA",
        "PANGOA",
        "RIO NEGRO",
        "RIO TAMBO",
        "VIZCATAN DEL ENE",
        "TARMA",
        "ACOBAMBA",
        "HUARICOLCA",
        "HUASAHUASI",
        "LA UNION",
        "PALCA",
        "PALCAMAYO",
        "SAN PEDRO DE CAJAS",
        "TAPO",
        "LA OROYA",
        "CHACAPALPA",
        "HUAY-HUAY",
        "MARCAPOMACOCHA",
        "MOROCOCHA",
        "PACCHA",
        "SANTA BARBARA DE CARHUACAYAN",
        "SANTA ROSA DE SACCO",
        "SUITUCANCHA",
        "YAULI",
        "CHUPACA",
        "AHUAC",
        "CHONGOS BAJO",
        "HUACHAC",
        "HUAMANCACA CHICO",
        "SAN JUAN DE ISCOS",
        "SAN JUAN DE JARPA",
        "TRES DE DICIEMBRE",
        "YANACANCHA"
    ),
    'PE-LAL' => array(
        "TRUJILLO",
        "EL PORVENIR",
        "FLORENCIA DE MORA",
        "HUANCHACO",
        "LA ESPERANZA",
        "LAREDO",
        "MOCHE",
        "POROTO",
        "SALAVERRY",
        "SIMBAL",
        "VICTOR LARCO HERRERA",
        "ASCOPE",
        "CHICAMA",
        "CHOCOPE",
        "MAGDALENA DE CAO",
        "PAIJAN",
        "RAZURI",
        "SANTIAGO DE CAO",
        "CASA GRANDE",
        "BOLIVAR",
        "BAMBAMARCA",
        "CONDORMARCA",
        "LONGOTEA",
        "UCHUMARCA",
        "UCUNCHA",
        "CHEPEN",
        "PACANGA",
        "PUEBLO NUEVO",
        "JULCAN",
        "CALAMARCA",
        "CARABAMBA",
        "HUASO",
        "OTUZCO",
        "AGALLPAMPA",
        "CHARAT",
        "HUARANCHAL",
        "LA CUESTA",
        "MACHE",
        "PARANDAY",
        "SALPO",
        "SINSICAP",
        "USQUIL",
        "SAN PEDRO DE LLOC",
        "GUADALUPE",
        "JEQUETEPEQUE",
        "PACASMAYO",
        "SAN JOSÉ",
        "TAYABAMBA",
        "BULDIBUYO",
        "CHILLIA",
        "HUANCASPATA",
        "HUAYLILLAS",
        "HUAYO",
        "ONGON",
        "PARCOY",
        "PATAZ",
        "PIAS",
        "SANTIAGO DE CHALLAS",
        "TAURIJA",
        "URPAY",
        "HUAMACHUCO",
        "CHUGAY",
        "COCHORCO",
        "CURGOS",
        "MARCABAL",
        "SANAGORAN",
        "SARIN",
        "SARTIMBAMBA",
        "SANTIAGO DE CHUCO",
        "ANGASMARCA",
        "CACHICADAN",
        "MOLLEBAMBA",
        "MOLLEPATA",
        "QUIRUVILCA",
        "SANTA CRUZ DE CHUCA",
        "SITABAMBA",
        "CASCAS",
        "LUCMA",
        "MARMOT",
        "SAYAPULLO",
        "VIRU",
        "CHAO",
        "GUADALUPITO",
    ),
    'PE-LAM' => array(
        "CHICLAYO",
        "CHONGOYAPE",
        "ETEN",
        "ETEN PUERTO",
        "JOSÉ LEONARDO ORTIZ",
        "LA VICTORIA",
        "LAGUNAS",
        "MONSEFU",
        "NUEVA ARICA",
        "OYOTUN",
        "PICSI",
        "PIMENTEL",
        "REQUE",
        "SANTA ROSA",
        "SAÑA",
        "CAYALTI",
        "PATAPO",
        "POMALCA",
        "PUCALA",
        "TUMAN",
        "",
        "FERREÑAFE",
        "CAÑARIS",
        "INCAHUASI",
        "MANUEL ANTONIO MESONES MURO",
        "PITIPO",
        "PUEBLO NUEVO",
        "",
        "LAMBAYEQUE",
        "CHOCHOPE",
        "ILLIMO",
        "JAYANCA",
        "MOCHUMI",
        "MORROPE",
        "MOTUPE",
        "OLMOS",
        "PACORA",
        "SALAS",
        "SAN JOSÉ",
        "TUCUME"
    ),
    'PE-LIM' => array(
        "LIMA",
        "ANCON",
        "ATE",
        "BARRANCO",
        "BREÑA",
        "CARABAYLLO",
        "CHACLACAYO",
        "CHORRILLOS",
        "CIENEGUILLA",
        "COMAS",
        "EL AGUSTINO",
        "INDEPENDENCIA",
        "JESUS MARIA",
        "LA MOLINA",
        "LA VICTORIA",
        "LINCE",
        "LOS OLIVOS",
        "LURIGANCHO",
        "LURIN",
        "MAGDALENA DEL MAR",
        "PUEBLO LIBRE",
        "MIRAFLORES",
        "PACHACAMAC",
        "PUCUSANA",
        "PUENTE PIEDRA",
        "PUNTA HERMOSA",
        "PUNTA NEGRA",
        "RIMAC",
        "SAN BARTOLO",
        "SAN BORJA",
        "SAN ISIDRO",
        "SAN JUAN DE LURIGANCHO",
        "SAN JUAN DE MIRAFLORES",
        "SAN LUIS",
        "SAN MARTIN DE PORRES",
        "SAN MIGUEL",
        "SANTA ANITA",
        "SANTA MARIA DEL MAR",
        "SANTA ROSA",
        "SANTIAGO DE SURCO",
        "SURQUILLO",
        "VILLA EL SALVADOR",
        "VILLA MARIA DEL TRIUNFO",
        "BARRANCA",
        "PARAMONGA",
        "PATIVILCA",
        "SUPE",
        "SUPE PUERTO",
        "CAJATAMBO",
        "COPA",
        "GORGOR",
        "HUANCAPON",
        "MANAS",
        "CANTA",
        "ARAHUAY",
        "HUAMANTANGA",
        "HUAROS",
        "LACHAQUI",
        "SAN BUENAVENTURA",
        "SANTA ROSA DE QUIVES",
        "SAN VICENTE DE CAÑETE",
        "ASIA",
        "CALANGO",
        "CERRO AZUL",
        "CHILCA",
        "COAYLLO",
        "IMPERIAL",
        "LUNAHUANA",
        "MALA",
        "NUEVO IMPERIAL",
        "PACARAN",
        "QUILMANA",
        "SAN ANTONIO",
        "SAN LUIS",
        "SANTA CRUZ DE FLORES",
        "ZUÑIGA",
        "HUARAL",
        "ATAVILLOS ALTO",
        "ATAVILLOS BAJO",
        "AUCALLAMA",
        "CHANCAY",
        "IHUARI",
        "LAMPIAN",
        "PACARAOS",
        "SAN MIGUEL DE ACOS",
        "SANTA CRUZ DE ANDAMARCA",
        "SUMBILCA",
        "VEINTISIETE DE NOVIEMBRE",
        "MATUCANA",
        "ANTIOQUIA",
        "CALLAHUANCA",
        "CARAMPOMA",
        "CHICLA",
        "CUENCA",
        "HUACHUPAMPA",
        "HUANZA",
        "HUAROCHIRI",
        "LAHUAYTAMBO",
        "LANGA",
        "LARAOS",
        "MARIATANA",
        "RICARDO PALMA",
        "SAN ANDRÉS DE TUPICOCHA",
        "SAN ANTONIO",
        "SAN BARTOLOMÉ",
        "SAN DAMIAN",
        "SAN JUAN DE IRIS",
        "SAN JUAN DE TANTARANCHE",
        "SAN LORENZO DE QUINTI",
        "SAN MATEO",
        "SAN MATEO DE OTAO",
        "SAN PEDRO DE CASTA",
        "SAN PEDRO DE HUANCAYRE",
        "SANGALLAYA",
        "SANTA CRUZ DE COCACHACRA",
        "SANTA EULALIA",
        "SANTIAGO DE ANCHUCAYA",
        "SANTIAGO DE TUNA",
        "SANTO DOMINGO DE LOS OLLEROS",
        "SURCO",
        "HUACHO",
        "AMBAR",
        "CALETA DE CARQUIN",
        "CHECRAS",
        "HUALMAY",
        "HUAURA",
        "LEONCIO PRADO",
        "PACCHO",
        "SANTA LEONOR",
        "SANTA MARIA",
        "SAYAN",
        "VEGUETA",
        "OYON",
        "ANDAJES",
        "CAUJUL",
        "COCHAMARCA",
        "NAVAN",
        "PACHANGARA",
        "YAUYOS",
        "ALIS",
        "ALLAUCA",
        "AYAVIRI",
        "AZANGARO",
        "CACRA",
        "CARANIA",
        "CATAHUASI",
        "CHOCOS",
        "COCHAS",
        "COLONIA",
        "HONGOS",
        "HUAMPARA",
        "HUANCAYA",
        "HUANGASCAR",
        "HUANTAN",
        "HUAÑEC",
        "LARAOS",
        "LINCHA",
        "MADEAN",
        "MIRAFLORES",
        "OMAS",
        "PUTINZA",
        "QUINCHES",
        "QUINOCAY",
        "SAN JOAQUIN",
        "SAN PEDRO DE PILAS",
        "TANTA",
        "TAURIPAMPA",
        "TOMAS",
        "TUPE",
        "VIÑAC",
        "VITIS"
    ),
    'PE-LMA' => array(
        "LIMA",
        "ANCON",
        "ATE",
        "BARRANCO",
        "BREÑA",
        "CARABAYLLO",
        "CHACLACAYO",
        "CHORRILLOS",
        "CIENEGUILLA",
        "COMAS",
        "EL AGUSTINO",
        "INDEPENDENCIA",
        "JESUS MARIA",
        "LA MOLINA",
        "LA VICTORIA",
        "LINCE",
        "LOS OLIVOS",
        "LURIGANCHO",
        "LURIN",
        "MAGDALENA DEL MAR",
        "PUEBLO LIBRE",
        "MIRAFLORES",
        "PACHACAMAC",
        "PUCUSANA",
        "PUENTE PIEDRA",
        "PUNTA HERMOSA",
        "PUNTA NEGRA",
        "RIMAC",
        "SAN BARTOLO",
        "SAN BORJA",
        "SAN ISIDRO",
        "SAN JUAN DE LURIGANCHO",
        "SAN JUAN DE MIRAFLORES",
        "SAN LUIS",
        "SAN MARTIN DE PORRES",
        "SAN MIGUEL",
        "SANTA ANITA",
        "SANTA MARIA DEL MAR",
        "SANTA ROSA",
        "SANTIAGO DE SURCO",
        "SURQUILLO",
        "VILLA EL SALVADOR",
        "VI+C1443:G1451LLA MARIA DEL TRIUNFO",
        "BARRANCA",
        "PARAMONGA",
        "PATIVILCA",
        "SUPE",
        "SUPE PUERTO",
        "CAJATAMBO",
        "COPA",
        "GORGOR",
        "HUANCAPON",
        "MANAS",
        "CANTA",
        "ARAHUAY",
        "HUAMANTANGA",
        "HUAROS",
        "LACHAQUI",
        "SAN BUENAVENTURA",
        "SANTA ROSA DE QUIVES",
        "SAN VICENTE DE CAÑETE",
        "ASIA",
        "CALANGO",
        "CERRO AZUL",
        "CHILCA",
        "COAYLLO",
        "IMPERIAL",
        "LUNAHUANA",
        "MALA",
        "NUEVO IMPERIAL",
        "PACARAN",
        "QUILMANA",
        "SAN ANTONIO",
        "SAN LUIS",
        "SANTA CRUZ DE FLORES",
        "ZUÑIGA",
        "HUARAL",
        "ATAVILLOS ALTO",
        "ATAVILLOS BAJO",
        "AUCALLAMA",
        "CHANCAY",
        "IHUARI",
        "LAMPIAN",
        "PACARAOS",
        "SAN MIGUEL DE ACOS",
        "SANTA CRUZ DE ANDAMARCA",
        "SUMBILCA",
        "VEINTISIETE DE NOVIEMBRE",
        "MATUCANA",
        "ANTIOQUIA",
        "CALLAHUANCA",
        "CARAMPOMA",
        "CHICLA",
        "CUENCA",
        "HUACHUPAMPA",
        "HUANZA",
        "HUAROCHIRI",
        "LAHUAYTAMBO",
        "LANGA",
        "LARAOS",
        "MARIATANA",
        "RICARDO PALMA",
        "SAN ANDRÉS DE TUPICOCHA",
        "SAN ANTONIO",
        "SAN BARTOLOMÉ",
        "SAN DAMIAN",
        "SAN JUAN DE IRIS",
        "SAN JUAN DE TANTARANCHE",
        "SAN LORENZO DE QUINTI",
        "SAN MATEO",
        "SAN MATEO DE OTAO",
        "SAN PEDRO DE CASTA",
        "SAN PEDRO DE HUANCAYRE",
        "SANGALLAYA",
        "SANTA CRUZ DE COCACHACRA",
        "SANTA EULALIA",
        "SANTIAGO DE ANCHUCAYA",
        "SANTIAGO DE TUNA",
        "SANTO DOMINGO DE LOS OLLEROS",
        "SURCO",
        "HUACHO",
        "AMBAR",
        "CALETA DE CARQUIN",
        "CHECRAS",
        "HUALMAY",
        "HUAURA",
        "LEONCIO PRADO",
        "PACCHO",
        "SANTA LEONOR",
        "SANTA MARIA",
        "SAYAN",
        "VEGUETA",
        "OYON",
        "ANDAJES",
        "CAUJUL",
        "COCHAMARCA",
        "NAVAN",
        "PACHANGARA",
        "YAUYOS",
        "ALIS",
        "ALLAUCA",
        "AYAVIRI",
        "AZANGARO",
        "CACRA",
        "CARANIA",
        "CATAHUASI",
        "CHOCOS",
        "COCHAS",
        "COLONIA",
        "HONGOS",
        "HUAMPARA",
        "HUANCAYA",
        "HUANGASCAR",
        "HUANTAN",
        "HUAÑEC",
        "LARAOS",
        "LINCHA",
        "MADEAN",
        "MIRAFLORES",
        "OMAS",
        "PUTINZA",
        "QUINCHES",
        "QUINOCAY",
        "SAN JOAQUIN",
        "SAN PEDRO DE PILAS",
        "TANTA",
        "TAURIPAMPA",
        "TOMAS",
        "TUPE",
        "VIÑAC",
        "VITIS"
    ),
    'PE-LOR' => array(
        "IQUITOS",
        "ALTO NANAY",
        "FERNANDO LORES",
        "INDIANA",
        "LAS AMAZONAS",
        "MAZAN",
        "NAPO",
        "PUNCHANA",
        "TORRES CAUSANA",
        "BELÉN",
        "SAN JUAN BAUTISTA",
        "YURIMAGUAS",
        "BALSAPUERTO",
        "JEBEROS",
        "LAGUNAS",
        "SANTA CRUZ",
        "TENIENTE CESAR LOPEZ ROJAS",
        "NAUTA",
        "PARINARI",
        "TIGRE",
        "TROMPETEROS",
        "URARINAS",
        "RAMON CASTILLA",
        "PEBAS",
        "YAVARI",
        "SAN PABLO",
        "REQUENA",
        "ALTO TAPICHE",
        "CAPELO",
        "EMILIO SAN MARTIN",
        "MAQUIA",
        "PUINAHUA",
        "SAQUENA",
        "SOPLIN",
        "TAPICHE",
        "JENARO HERRERA",
        "YAQUERANA",
        "CONTAMANA",
        "INAHUAYA",
        "PADRE MARQUEZ",
        "PAMPA HERMOSA",
        "SARAYACU",
        "VARGAS GUERRA",
        "BARRANCA",
        "CAHUAPANAS",
        "MANSERICHE",
        "MORONA",
        "PASTAZA",
        "ANDOAS",
        "PUTUMAYO",
        "ROSA PANDURO",
        "TENIENTE MANUEL CLAVERO",
        "YAGUAS",
    ),
    'PE-MDD' => array(
        "TAMBOPATA",
        "INAMBARI",
        "LAS PIEDRAS",
        "LABERINTO",
        "",
        "MANU",
        "FITZCARRALD",
        "MADRE DE DIOS",
        "HUEPETUHE",
        "",
        "IÑAPARI",
        "IBERIA",
        "TAHUAMANU",
    ),
    'PE-MOQ' => array(
        "MOQUEGUA",
        "CARUMAS",
        "CUCHUMBAYA",
        "SAMEGUA",
        "SAN CRISTOBAL",
        "TORATA",
        "OMATE",
        "CHOJATA",
        "COALAQUE",
        "ICHUÑA",
        "LA CAPILLA",
        "LLOQUE",
        "MATALAQUE",
        "PUQUINA",
        "QUINISTAQUILLAS",
        "UBINAS",
        "YUNGA",
        "ILO",
        "EL ALGARROBAL",
        "PACOCHA",

    ),
    'PE-PAS' => array(
        "CHAUPIMARCA",
        "HUACHON",
        "HUARIACA",
        "HUAYLLAY",
        "NINACACA",
        "PALLANCHACRA",
        "PAUCARTAMBO",
        "SAN FRANCISCO DE ASIS DE YARUSYACAN",
        "SIMON BOLIVAR",
        "TICLACAYAN",
        "TINYAHUARCO",
        "VICCO",
        "YANACANCHA",
        "YANAHUANCA",
        "CHACAYAN",
        "GOYLLARISQUIZGA",
        "PAUCAR",
        "SAN PEDRO DE PILLAO",
        "SANTA ANA DE TUSI",
        "TAPUC",
        "VILCABAMBA",
        "OXAPAMPA",
        "CHONTABAMBA",
        "HUANCABAMBA",
        "PALCAZU",
        "POZUZO",
        "PUERTO BERMUDEZ",
        "VILLA RICA",
        "CONSTITUCION",
    ),
    'PE-PIU' => array(
        "PIURA",
        "CASTILLA",
        "ATACAOS",
        "CURA MORI",
        "EL TALLAN",
        "LA ARENA",
        "LA UNION",
        "LAS LOMAS",
        "TAMBO GRANDE",
        "VEINTISEIS DE OCTUBRE",
        "AYABACA",
        "FRIAS",
        "JILILI",
        "LAGUNAS",
        "MONTERO",
        "PACAIPAMPA",
        "PAIMAS",
        "SAPILLICA",
        "SICCHEZ",
        "SUYO",
        "HUANCABAMBA",
        "CANCHAQUE",
        "EL CARMEN DE LA FRONTERA",
        "HUARMACA",
        "LALAQUIZ",
        "SAN MIGUEL DE EL FAIQUE",
        "SONDOR",
        "SONDORILLO",
        "CHULUCANAS",
        "BUENOS AIRES",
        "CHALACO",
        "LA MATANZA",
        "MORROPON",
        "SALITRAL",
        "SAN JUAN DE BIGOTE",
        "SANTA CATALINA DE MOSSA",
        "SANTO DOMINGO",
        "YAMANGO",
        "PAITA",
        "AMOTAPE",
        "ARENAL",
        "COLAN",
        "LA HUACA",
        "TAMARINDO",
        "VICHAYAL",
        "SULLANA",
        "BELLAVISTA",
        "IGNACIO ESCUDERO",
        "LANCONES",
        "MARCAVELICA",
        "MIGUEL CHECA",
        "QUERECOTILLO",
        "SALITRAL",
        "PARIÑAS",
        "EL ALTO",
        "LA BREA",
        "LOBITOS",
        "LOS ORGANOS",
        "MANCORA",
        "SECHURA",
        "BELLAVISTA DE LA UNION",
        "BERNAL",
        "CRISTO NOS VALGA",
        "VICE",
        "RINCONADA LLICUAR",
    ),
    'PE-PUN' => array(
        "PUNO",
        "ACORA",
        "AMANTANI",
        "ATUNCOLLA",
        "CAPACHICA",
        "CHUCUITO",
        "COATA",
        "HUATA",
        "MAÑAZO",
        "PAUCARCOLLA",
        "PICHACANI",
        "PLATERIA",
        "SAN ANTONIO",
        "TIQUILLACA",
        "VILQUE",
        "AZANGARO",
        "ACHAYA",
        "ARAPA",
        "ASILLO",
        "CAMINACA",
        "CHUPA",
        "JOSÉ DOMINGO CHOQUEHUANCA",
        "MUÑANI",
        "POTONI",
        "SAMAN",
        "SAN ANTON",
        "SAN JOSÉ",
        "SAN JUAN DE SALINAS",
        "SANTIAGO DE PUPUJA",
        "TIRAPATA",
        "MACUSANI",
        "AJOYANI",
        "AYAPATA",
        "COASA",
        "CORANI",
        "CRUCERO",
        "ITUATA",
        "OLLACHEA",
        "SAN GABAN",
        "USICAYOS",
        "JULI",
        "DESAGUADERO",
        "HUACULLANI",
        "KELLUYO",
        "PISACOMA",
        "POMATA",
        "ZEPITA",
        "ILAVE",
        "CAPAZO",
        "PILCUYO",
        "SANTA ROSA",
        "CONDURIRI",
        "HUANCANE",
        "COJATA",
        "HUATASANI",
        "INCHUPALLA",
        "PUSI",
        "ROSASPATA",
        "TARACO",
        "VILQUE CHICO",
        "LAMPA",
        "CABANILLA",
        "CALAPUJA",
        "NICASIO",
        "OCUVIRI",
        "PALCA",
        "PARATIA",
        "PUCARA",
        "SANTA LUCIA",
        "VILAVILA",
        "AYAVIRI",
        "ANTAUTA",
        "CUPI",
        "LLALLI",
        "MACARI",
        "NUÑOA",
        "ORURILLO",
        "SANTA ROSA",
        "UMACHIRI",
        "MOHO",
        "CONIMA",
        "HUAYRAPATA",
        "TILALI",
        "PUTINA",
        "ANANEA",
        "PEDRO VILCA APAZA",
        "QUILCAPUNCU",
        "SINA",
        "JULIACA",
        "CABANA",
        "CABANILLAS",
        "CARACOTO",
        "SANDIA",
        "CUYOCUYO",
        "LIMBANI",
        "PATAMBUCO",
        "PHARA",
        "QUIACA",
        "SAN JUAN DEL ORO",
        "YANAHUAYA",
        "ALTO INAMBARI",
        "SAN PEDRO DE PUTINA PUNCO",
        "YUNGUYO",
        "ANAPIA",
        "COPANI",
        "CUTURAPI",
        "OLLARAYA",
        "TINICACHI",
        "UNICACHI",
    ),
    'PE-SAM' => array(
        "MOYOBAMBA",
        "CALZADA",
        "HABANA",
        "JEPELACIO",
        "SORITOR",
        "YANTALO",
        "BELLAVISTA",
        "ALTO BIAVO",
        "BAJO BIAVO",
        "HUALLAGA",
        "SAN PABLO",
        "SAN RAFAEL",
        "SAN JOSÉ DE SISA",
        "AGUA BLANCA",
        "SAN MARTIN",
        "SANTA ROSA",
        "SHATOJA",
        "SAPOSOA",
        "ALTO SAPOSOA",
        "EL ESLABON",
        "PISCOYACU",
        "SACANCHE",
        "TINGO DE SAPOSOA",
        "LAMAS",
        "ALONSO DE ALVARADO",
        "BARRANQUITA",
        "CAYNARACHI",
        "CUÑUMBUQUI",
        "PINTO RECODO",
        "RUMISAPA",
        "SAN ROQUE DE CUMBAZA",
        "SHANAO",
        "TABALOSOS",
        "ZAPATERO",
        "JUANJUI",
        "CAMPANILLA",
        "HUICUNGO",
        "PACHIZA",
        "PAJARILLO",
        "PICOTA",
        "BUENOS AIRES",
        "CASPISAPA",
        "PILLUANA",
        "PUCACACA",
        "SAN CRISTOBAL",
        "SAN HILARION",
        "SHAMBOYACU",
        "TINGO DE PONASA",
        "TRES UNIDOS",
        "RIOJA",
        "AWAJUN",
        "ELIAS SOPLIN VARGAS",
        "NUEVA CAJAMARCA",
        "PARDO MIGUEL",
        "POSIC",
        "SAN FERNANDO",
        "YORONGOS",
        "YURACYACU",
        "TARAPOTO",
        "ALBERTO LEVEAU",
        "CACATACHI",
        "CHAZUTA",
        "CHIPURANA",
        "EL PORVENIR",
        "HUIMBAYOC",
        "JUAN GUERRA",
        "LA BANDA DE SHILCAYO",
        "MORALES",
        "PAPAPLAYA",
        "SAN ANTONIO",
        "SAUCE",
        "SHAPAJA",
        "TOCACHE",
        "NUEVO PROGRESO",
        "POLVORA",
        "SHUNTE",
        "UCHIZA"
    ),
    'PE-TAC' => array(
        "TACNA",
        "ALTO DE LA ALIANZA",
        "CALANA",
        "CIUDAD NUEVA",
        "INCLAN",
        "PACHIA",
        "PALCA",
        "POCOLLAY",
        "SAMA",
        "CORONEL GREGORIO ALBARRACIN LANCHIPA",
        "CANDARAVE",
        "CAIRANI",
        "CAMILACA",
        "CURIBAYA",
        "HUANUARA",
        "QUILAHUANI",
        "LOCUMBA",
        "ILABAYA",
        "ITE",
        "TARATA",
        "HÉROES ALBARRACIN",
        "ESTIQUE",
        "ESTIQUE-PAMPA",
        "SITAJARA",
        "SUSAPAYA",
        "TARUCACHI",
        "TICACO",
    ),
    'PE-TUM' => array(
        "TUMBES",
        "CORRALES",
        "LA CRUZ",
        "PAMPAS DE HOSPITAL",
        "SAN JACINTO",
        "SAN JUAN DE LA VIRGEN",
        "ZORRITOS",
        "CASITAS",
        "CANOAS DE PUNTA SAL",
        "ZARUMILLA",
        "AGUAS VERDES",
        "MATAPALO",
        "PAPAYAL",

    ),
    'PE-UCA' => array(
        "CALLERIA",
        "CAMPOVERDE",
        "IPARIA",
        "MASISEA",
        "YARINACOCHA",
        "NUEVA REQUENA",
        "MANANTAY",
        "RAYMONDI",
        "SEPAHUA",
        "TAHUANIA",
        "YURUA",
        "PADRE ABAD",
        "IRAZOLA",
        "CURIMANA",
        "NESHUYA",
        "ALEXANDER VON HUMBOLDT",
        "PURUS",
    ),
);
