<?php

/**
 * Paraguay places
 * 
 */
global $places;

$places['PY'] = [

    "0" => ["Asunción"],
    "1" => [
        "Horqueta",
        "Belén",
        "Azotey",
        "Paso Barreto",
        "Concepción",
        "Loreto",
        "Yby Ya'u",
    ],
    "2" => [
        "Choré",
        "Santani",
        "Capiibary",
        "Unión",
        "Gral. Resquín",
        "Santa Rosa del Aguaray",
        "Puerto Rosario",
        "Gral. Elizardo Aquino",
        "Liberación",
        "25 de Diciembre",
        "Antequera",
        "Guayaybi",
        "Lima",
        "Itacurubí del Rosario",
        "San Pedro del Ycuamandiyú",
    ],
    "3" => [
        "Arroyos y Esteros",
        "Atyra",
        "Santa Elena",
        "Eusebio Ayala",
        "San Bernardino",
        "Altos",
        "Isla Pucu",
        "Itacurubí de la Cordillera",
        "San José Obrero",
        "Valenzuela",
        "1ro. De marzo",
        "Tobatí",
        "Piribebuy",
        "Caacupe",
        "Caraguatay",
    ],
    "4" => [
        "Iturbe",
        "Mbocayaty",
        "Dr. Botrel",
        "San Salvador",
        "Natalicio Talavera",
        "Mauricio Jose Troche",
        "José Fassardi",
        "Coronel Martinez",
        "Tebicuary",
        "Borja",
        "Eugenio A. Garay",
        "Itapé",
        "Villarrica",
        "Ñumi",
        "Felix Perez Cardozo",
        "Paso Yobai",
        "Colonia Independencia",
    ],
    "5" => [
        "Juan Manuel Frutos (Pastoreo)",
        "Caaguazú",
        "Santa Rosa del Mbutuy",
        "Yhu",
        "Carayao",
        "San Joaquin",
        "RI 3 Corrales",
        "Repatriación",
        "San José de los Arroyos",
        "Vaquería",
        "Nueva Londres",
        "Campo 9",
        "Simon Bolivar",
        "Cecilio Báez",
        "Coronel Oviedo",
    ],
    "6" => [
        "Maciel",
        "Moises Bertoni",
        "Higinio Morinigo",
        "Yuty",
        "Buena Vista",
        "Caazapá",
        "San Juan Nepomuceno",
        "Fulgencio Yegros",
    ],
    "7" => [
        "Tomas Romero Pereira",
        "San Pedro del Paraná",
        "Natalio",
        "Coronel Bogado",
        "Colonia Fram",
        "Encarnación",
        "Capitan Miranda",
        "Capitán Meza",
        "Gral. Artigas",
        "San Rafael del Paraná",
        "La Paz",
        "Maria Auxiliadora",
        "Kimex (Colonia Carlos A. López)",
        "Cambyreta",
        "Obligado",
        "Edelira 28",
        "San Cosme Y Damián",
        "Pirapo",
        "Bella Vista Sur",
        "Mayor Otaño",
        "Edelira",
        "Carmen del Paraná",
        "Hohenau",
        "San Juan del Paraná",
        "Gral. Delgado",
        "Yatytay",
    ],
    "8" => [
        "San Patricio",
        "San Ignacio Misiones",
        "San Juan Bautista",
        "Ayolas",
        "Santiago Misiones",
        "Santa Rosa Misiones",
        "Santa María Misiones",
    ],
    "9" => [
        "Ybycui",
        "Carapeguá",
        "Pirayú",
        "Escobar",
        "Sapucai",
        "La Colmena",
        "Caballero",
        "Yaguaron",
        "Paraguarí",
        "Acahay",
        "Quiindy",
        "Ybytymí",
        "San Roque Gonzalez",
    ],
    "10" => [
        "Santa Fe del Paraná",
        "Colonia Yguazu",
        "Minga Porá",
        "Itakyry",
        "Juan E. O'Leary",
        "Naranjal",
        "Minga Guazú",
        "Domingo Martinez de Irala",
        "Ciudad del Este",
        "Cedrales",
        "Iruña",
        "San Alberto",
        "Hernandarias",
        "Santa Rita",
        "Juan León Malloriquin",
        "San Cristobal",
        "SANTA ROSA DEL MONDAY",
        "Nueva Fortuna",
        "Puerto Pdte. Franco",
    ],
    "11" => [
        "San Antonio",
        "Ypane",
        "Lambaré",
        "Itagua",
        "Limpio",
        "Villa Elisa",
        "San Lorenzo",
        "Itá",
        "Nueva Italia",
        "Capiatá",
        "Ypacarai",
        "Ñemby",
        "José Agusto Saldivar",
        "Areguá",
        "Luque",
        "Fernando de la Mora",
        "Villeta",
        "Mariano Roque Alonso",
        "Guarambaré",
    ],
    "12" => ["Pilar", "Alberdi", "Villa Oliva"],
    "13" => [
        "Pedro Juan Caballero",
        "Sanja Pyta",
        "Bella Vista Norte",
        "Capitán Bado",
    ],
    "14" => [
        "Corpus Christi",
        "Curuguaty",
        "Salto del Guaira",
        "La Paloma",
        "Puente Kyha",
        "Nueva Esperanza",
        "Katuete",
    ],
    "15" => ["Villa Hayes", "Benjamín Aceval"],
    "16" => ["Filadelfia", "Loma Plata"],


];
